services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tarefacil
    restart: always
    environment:
      MYSQL_DATABASE: BDTareFacil
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
      MYSQL_ROOT_PASSWORD: Root@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_tarefacil_data:/var/lib/mysql

volumes:
  mysql_tarefacil_data: